{
 "title": "Mongo Cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Server restarts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(resets(mongo_server_uptime_seconds[3m]))"
    }
   ]
  },
  {
   "title": "Operations/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongo_opcounters_total[3m]))"
    }
   ]
  },
  {
   "title": "Slow Query Notifications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(mongo_log_slowquery_seconds_count{command!=\"isMaster\"}[3m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(mongo_connections{type=\"current\"})",
     "legendFormat": "Open"
    },
    {
     "expr": "sum(mongo_connections{type=\"active\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Connections in 1h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(delta(mongo_log_client_metadata_total[1h])) by (driver) > 0",
     "legendFormat": "{{driver}}"
    }
   ]
  },
  {
   "title": "Slow Queries - Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mongo_log_slowquery_seconds_sum{command!=\"isMaster\"}[3m])/rate(mongo_log_slowquery_seconds_count{command!=\"isMaster\"}[3m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongo_opcounters_total[3m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Slow Queries - Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongo_log_slowquery_seconds_count{command!=\"isMaster\"}[3m])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongo_connections{type!=\"available\", type!=\"totalCreated\"}) by (type, host)",
     "legendFormat": "{{host}} {{type}}"
    }
   ]
  },
  {
   "title": "Shard documents",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mongo_collection_shard_doc_count",
     "legendFormat": "{{db}}:{{collection}}:{{shard}}"
    }
   ]
  },
  {
   "title": "Shard growth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mongo_collection_shard_disk_bytes[1h])>0",
     "legendFormat": "{{db}}:{{collection}}:{{shard}}"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "mongo_database_disk_bytes", "legendFormat": "{{db}}" }
   ]
  }
 ]
}